# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 075ab54b45630a47995c9b3c4efa429194ecaf683d3f83cab8377203838815f52a64573bdde3cb5da73f851be3f0f702bcab45101bf0c158914635650277ebcf

test:
  secret_key_base: 3e3e16b3685f3b2e675fc7fc0cdcc4a0c6519c20b2387858cfe1dc4ad110a1c2068f5b1e06f2154e47f48500ac21187968de893c4ba8f3b5344b12ef9d117084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
